# Generated by Django 4.2 on 2025-01-20 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_organization_subdivisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='sub_sub_division',
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='sub_sub_division',
            field=models.ManyToManyField(blank=True, to='models.subsubdivision'),
        ),
    ]
