# Generated by Django 4.2 on 2025-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_remove_employee_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
