# Generated by Django 4.2 on 2025-01-27 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_employee_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendareducation',
            name='employees',
            field=models.ManyToManyField(related_name='calendar_education_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
