# Generated by Django 4.2 on 2025-02-05 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_calendareducation_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
