# Generated by Django 4.2 on 2025-02-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_event_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_dismissal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
